# Generated by Django 4.2.1 on 2023-05-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, unique=True, verbose_name='Group Title')),
                ('group_password', models.CharField(max_length=100, verbose_name='Group Password')),
                ('group_description', models.TextField(verbose_name='Group Description')),
                ('group_owner_id', models.PositiveSmallIntegerField(verbose_name='Group Owner ID')),
                ('group_create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Group Create Date and Time')),
                ('group_edit_datetime', models.DateTimeField(auto_now=True, verbose_name='Group Edit Date and Time')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_member_id', models.PositiveSmallIntegerField(verbose_name='Group Member ID')),
                ('group_member_is_admin', models.BooleanField(default=False, verbose_name='Group Member is Admin')),
                ('group_id', models.PositiveSmallIntegerField(verbose_name='Group ID')),
                ('member_join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
