# Generated by Django 4.2.1 on 2023-05-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=150, verbose_name='Todo Title')),
                ('todo_description', models.TextField(verbose_name='Todo Description')),
                ('todo_is_complete', models.BooleanField(default=False, verbose_name='Todo is Complete')),
                ('todo_create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Todo Create Date and Time')),
                ('todo_edit_datetime', models.DateTimeField(auto_now=True, verbose_name='Todo Edit Date and Time')),
                ('todo_owner_id', models.PositiveSmallIntegerField(verbose_name='Todo Owner ID')),
                ('todo_group_id', models.PositiveSmallIntegerField(verbose_name='Todo Group ID')),
            ],
        ),
    ]
