# Generated by Django 4.2.1 on 2023-05-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_description',
        ),
    ]
