# Generated by Django 4.2.1 on 2023-05-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_owner_name',
            field=models.CharField(default='default name', max_length=100, verbose_name='Todo Owner Name'),
            preserve_default=False,
        ),
    ]
